#version: "3.9"

services:
  backend:
    image: php:8.2-fpm
    container_name: backend
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend
      - ./backend/vendor:/var/www/backend/vendor
    depends_on:
      - db
      - redis
    build:
      context: .
      dockerfile: ./backend/Dockerfile  
    environment:
      DATABASE_URL: "pgsql://postgres:postgres@db:5432/poc_db"
      REDIS_URL: "redis://redis:6379"
      JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"
      JWT_EXPIRATION: "3600"
      SOAP_WSDL_URL: "http://techn5292.eu.techem.corp:8081/Main.asmx?wsdl"
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public  
    networks:
      - app-network


  frontend:
    image: node:20
    container_name: frontend
    working_dir: /var/www/frontend
    volumes:
      - ./frontend:/var/www/frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile   
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    command: sh -c "CHOKIDAR_USEPOLLING=true yarn install && CHOKIDAR_USEPOLLING=true yarn dev"
    networks:
      - app-network


  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: poc_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network      

volumes:
  pgdata:


networks:
  app-network:
    driver: bridge

