version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_local
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./backend:/var/www/backend:ro
      - ./storage/documents:/var/www/storage/documents:ro
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: php:8.4-fpm
    container_name: backend_local
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend
      - ./backend/vendor:/var/www/backend/vendor
      - ./storage/documents:/var/www/storage/documents
    depends_on:
      - db
      - redis
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      DATABASE_URL: "pgsql://postgres:postgres@db:5432/poc_db"
      REDIS_URL: "redis://redis:6379"
      JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"
      JWT_EXPIRATION: "3600"
      SOAP_WSDL_URL: "http://techn5292.eu.techem.corp:8083/Main.asmx?wsdl"
      CALLBACK_URL_BASE: "http://techn5274:83"
      DOCUMENT_STORAGE_PATH: "/var/www/storage/documents"
      DOCUMENT_URL_PREFIX: "/documents"
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
    networks:
      - app-network

  frontend:
    image: node:20
    container_name: frontend_local
    working_dir: /var/www/frontend
    volumes:
      - ./frontend:/var/www/frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    command: sh -c "CHOKIDAR_USEPOLLING=true yarn install && CHOKIDAR_USEPOLLING=true yarn dev"
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: poc_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis_local
    ports:
      - "6379:6379"
    networks:
      - app-network

  redis-exporter:
    image: bitnami/redis-exporter:latest
    container_name: redis-exporter_local
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: redis://redis:6379
    depends_on:
      - redis
    networks:
      - app-network    

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander_local
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - app-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_local
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - app-network

  mercure:
    image: dunglas/mercure
    container_name: mercure
    ports:
      - "9090:80"
    environment:
      SERVER_NAME: ":80"
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
      MERCURE_EXTRA_DIRECTIVES: |
        metrics
        cors_origins http://localhost:3000
        anonymous
    networks:
      - app-network

  varnish:
    image: varnish:7
    container_name: varnish_local
    ports:
      - "8080:80"
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    depends_on:
      - backend
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus_local
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - app-network

  varnish-exporter:
    build:
      context: ./varnish-exporter
    container_name: varnish-exporter_local
    ports:
      - "9131:9131"
    depends_on:
      - varnish
    networks:
      - app-network


  grafana:
    image: grafana/grafana
    container_name: grafana_local
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-network

volumes:
  pgdata:
  portainer_data:
  grafana-storage:

networks:
  app-network:
    driver: bridge