nelmio_cors:
  defaults:
    origin_regex: false
    allow_origin: ["*"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    allow_headers: ["Content-Type", "Authorization", "X-Request-ID"]
    expose_headers: ["Link", "X-Request-ID"]
    max_age: 3600
    allow_credentials: false
  paths:
    "^/api/":
      allow_origin: ["*"]
      allow_headers: ["Content-Type", "Authorization", "X-Request-ID"]
      allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
      max_age: 3600
