global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'varnish'
    static_configs:
      - targets: ['varnish-exporter:9131']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
  - job_name: 'mercure'
    static_configs:
      - targets: ['mercure:80']
        labels:
          group: 'mercure'

    
